#!/bin/bash


# $1 = system folder

GENERATE=0

if [ "$#" -ne 1 ]; then
    echo "  \$1 = non-inlined system folder"
    exit
fi

log=$2"/log.txt"
system=`ls $1`
sysroot=`basename $1`

for sys in $system; do
    rm $1/$sys/*_oracle.csv 2> /dev/null
    rm $1/$sys/*_oracles.csv 2> /dev/null
    rm $1/$sys/obligations/*_coverage.csv 2> /dev/null
    #rm -r $1/$sys/mutants 2> /dev/null
    #rm -r $1/$sys/equivalentMutants 2> /dev/null
    #rm -r $1/$sys/metadata 2> /dev/null
done
