config_coverage=("mcdc" "obc")
config_jvm_memory="16384m"
#config_jvm_memory="4096m"
config_obc_types=("J" "JSMB")
config_universal_suite=true
config_generate_tests=false
config_generate_mutants=false
config_check_equivalence=false
config_n_cores=4
config_mc_timeout=30
config_debug=false
config_compiler=gcc
config_compiler=gcc
